//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AliExpressJobLog
    {
        public int Id { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<long> SuccessItemCount { get; set; }
        public string ContentId { get; set; }
        public string Result { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ProductDetails { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
