//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AliExpressCategory
    {
        public int ID { get; set; }
        public long AliExpressCategoryID { get; set; }
        public string AliExpressCategoryName { get; set; }
        public Nullable<long> AliExpressParentCategoryID { get; set; }
        public bool AliExpressCategoryIsLeaf { get; set; }
        public long AliExpressCategoryLevel { get; set; }
        public string AliCategoryFullPath { get; set; }
    }
}
