//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class aliexpressorderitem
    {
        public int ID { get; set; }
        public string AliExpressProductID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<int> ItemCreatedBy { get; set; }
        public Nullable<System.DateTime> ItemCreatedWhen { get; set; }
        public Nullable<int> ItemModifyBy { get; set; }
        public Nullable<System.DateTime> ItemModifyWhen { get; set; }
        public Nullable<long> AliExpressOrderId { get; set; }
        public Nullable<bool> AliExpressProductOrderId { get; set; }
        public Nullable<int> SCOrderId { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string SkuCode { get; set; }
    }
}
