//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int OrderID { get; set; }
        public string AliExpressOrderID { get; set; }
        public string AliExpressProductId { get; set; }
        public string OrignalProductId { get; set; }
        public string OrignalProductLink { get; set; }
        public string ProductTitle { get; set; }
        public string DeliveryCountry { get; set; }
        public string ShippingWeight { get; set; }
        public string OrderAmount { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string SellerID { get; set; }
        public string SellerEmail { get; set; }
        public Nullable<sbyte> productExist { get; set; }
        public string LogisticName { get; set; }
        public string LogisticType { get; set; }
        public Nullable<int> ItemCreatedBy { get; set; }
        public Nullable<System.DateTime> ItemCreatedWhen { get; set; }
        public Nullable<int> ItemModifyBy { get; set; }
        public Nullable<System.DateTime> ItemModifyWhen { get; set; }
    }
}
