//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderapiresult
    {
        public int OrderApiResultsID { get; set; }
        public int SC_OrderID { get; set; }
        public string AliExpressOrderID { get; set; }
        public string LogisticsServiceId { get; set; }
        public string LogisticsNumber { get; set; }
        public byte[] CainiaoLabel { get; set; }
        public Nullable<long> WarehouseOrderId { get; set; }
        public string Error { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string getonlinelogisticsserviceResponse { get; set; }
        public string createwarehouseorderResponse { get; set; }
        public string getLogisticNumberResponse { get; set; }
        public string getprintinfoResponse { get; set; }
        public string OrderFulfillResponse { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
    }
}
