//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentprofile
    {
        public int PaymentProfileID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardType { get; set; }
        public string ExpiryDate { get; set; }
        public string NameOnCard { get; set; }
        public Nullable<sbyte> IsDefault { get; set; }
        public Nullable<int> ItemCreatedBy { get; set; }
        public Nullable<System.DateTime> ItemCreatedWhen { get; set; }
        public Nullable<int> ItemModifyBy { get; set; }
        public Nullable<System.DateTime> ItemModifyWhen { get; set; }
        public Nullable<sbyte> IsAgreedPaymentPolicy { get; set; }
        public Nullable<System.DateTime> AgreedPaymentPolicyTime { get; set; }
        public Nullable<long> AuthorizeNetProfileId { get; set; }
        public string StripePaymentMethodId { get; set; }
    }
}
