//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Title { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public string SellingPriceCurrency { get; set; }
        public string OriginalProductID { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public string Inventory { get; set; }
        public string ManufacturerName { get; set; }
        public string ExternalCode { get; set; }
        public string ExternalCodeType { get; set; }
        public Nullable<int> ParentProductID { get; set; }
        public Nullable<int> NoOfCustomerReviews { get; set; }
        public Nullable<int> CustomerReviewRating { get; set; }
        public string NetWeight { get; set; }
        public string ShippingWeight { get; set; }
        public string CountryOfOrigin { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string SourceWebsite { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ItemCreatedBy { get; set; }
        public Nullable<System.DateTime> ItemCreatedWhen { get; set; }
        public Nullable<int> ItemModifyBy { get; set; }
        public Nullable<System.DateTime> ItemModifyWhen { get; set; }
    }
}
