//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMedia
    {
        public int ProductMediaID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<bool> MediaType { get; set; }
        public string MediaExt { get; set; }
        public string MediaLink { get; set; }
        public Nullable<bool> IsMainImage { get; set; }
        public Nullable<int> ItemCreatedBy { get; set; }
        public Nullable<System.DateTime> ItemCreatedWhen { get; set; }
    }
}
