//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellerspickedproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sellerspickedproduct()
        {
            this.sellerpickedproductskus = new HashSet<sellerpickedproductsku>();
        }
    
        public int SellersPickedID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<long> ParentProductID { get; set; }
        public Nullable<double> SellerPrice { get; set; }
        public string AliExpressProductID { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<int> ItemCreatedBy { get; set; }
        public Nullable<System.DateTime> ItemCreatedWhen { get; set; }
        public Nullable<int> ItemModifyBy { get; set; }
        public Nullable<System.DateTime> ItemModifyWhen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sellerpickedproductsku> sellerpickedproductskus { get; set; }
    }
}
