//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropshipPlatform.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class trackbackendserice
    {
        public long ID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> ServiceLastCall { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
